baseURL = "https://ben.gnoinski.ca"
languageCode = "en-us"
title = "Ben Gnoinski"
theme = "hyde-hyde"

[params]
  description = "DevOps Engineer"
  IncludeCustomCss = true

[params.social]
  github = "BGnoinski"
  linkedin = "ben-gnoinski-34b10890"
